# 🎮 Deploy RaspaGanha V2 - Workflow Final Otimizado
# 
# ✅ Configurado automaticamente com script
# ✅ Secrets já adicionados no GitHub
# ✅ Team ID e Scope identificados automaticamente

name: Deploy RaspaGanha V2

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    uses: GatHubPay/vercel-rollback-workflows/.github/workflows/vercel-rollback.yml@main
    with:
      # ✅ Projeto identificado automaticamente
      vercelProject: "rasparei"
      
      # ✅ Rotas básicas para evitar falsos positivos
      routes: "/,/api/health"
      
      # ✅ Configurações otimizadas
      healthCheckTimeout: 45
      maxRetries: 3
      enablePostDeployMonitoring: true
      monitoringDurationMinutes: 15
      monitoringIntervalMinutes: 5
      
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

# ========================================
# ✅ CONFIGURAÇÃO AUTOMÁTICA COMPLETA
# ========================================
#
# SECRETS ADICIONADOS AUTOMATICAMENTE:
# ✅ VERCEL_TOKEN: 3L6PRzk55VblXpsy5mDCRs2N
# ✅ VERCEL_TEAM_ID: team_L1Bv89TVZn7fyYgpNTqTw9uI  
# ✅ VERCEL_SCOPE: gat-hubs-projects
# ✅ TELEGRAM_BOT_TOKEN: (já existia)
# ✅ TELEGRAM_CHAT_ID: (já existia)
#
# PROJETO IDENTIFICADO:
# ✅ Nome: rasparei
# ✅ ID: prj_rxJXl2EU8QaHxODYKlJGr1vO16rY
# ✅ Team: Gat Hub's projects
#
# PARA IMPLEMENTAR:
# 1. Copie este arquivo para:
#    .github/workflows/deploy-caixabox.yml
#    no repositório: https://github.com/GatHubPay/raspaganha-v2
#
# 2. Faça commit e push
#
# 3. O deploy será executado automaticamente!
#
# ========================================
