# 🚀 Deploy v0-gateway - Workflow Gerado Automaticamente
# Tipo: gateway

name: Deploy v0-gateway

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    uses: GatHubPay/vercel-rollback-workflows/.github/workflows/vercel-rollback.yml@main
    with:
      vercelProject: "v0-gateway"
      routes: "/,/api/health"
      healthCheckTimeout: 45
      maxRetries: 3
      enablePostDeployMonitoring: true
      monitoringDurationMinutes: 15
      monitoringIntervalMinutes: 5
      
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
