# 游 Template B치sico - Deploy com Rollback Autom치tico
# 
# INSTRU칂칏ES:
# 1. Copie este arquivo para .github/workflows/deploy.yml no seu projeto
# 2. Substitua "SEU_PROJETO_VERCEL" pelo nome exato do projeto no Vercel
# 3. Configure os secrets necess치rios no GitHub
# 4. Fa칞a push e veja a m치gica acontecer!

name: Deploy Autom치tico com Rollback

on:
  push:
    branches: [main, master]
  workflow_dispatch: # Permite executar manualmente

jobs:
  deploy:
    uses: SeuUsuario/vercel-rollback-workflows/.github/workflows/vercel-rollback.yml@v1
    with:
      # 拘勇 OBRIGAT칍RIO: Nome EXATO do seu projeto no Vercel
      vercelProject: "SEU_PROJETO_VERCEL"
      
      # 拘勇 OPCIONAL: Rotas espec칤ficas para testar (deixe vazio para auto-detec칞칚o)
      routes: ""
      
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

# ========================================
# SECRETS NECESS츼RIOS NO GITHUB
# ========================================
# 
# V치 em Settings > Secrets and variables > Actions
# e adicione estes 3 secrets:
#
# VERCEL_TOKEN: (crie em https://vercel.com/account/tokens)
# VERCEL_TEAM_ID: (encontre no dashboard do Vercel)
# VERCEL_SCOPE: (nome da sua organiza칞칚o/time no Vercel)
#
# ========================================
