# 📝 Template Blog - Deploy com Rollback Automático
# 
# Otimizado para blogs, sites de conteúdo e portfólios
# Testa páginas de conteúdo e APIs de posts

name: Deploy Blog com Rollback

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    uses: SeuUsuario/vercel-rollback-workflows/.github/workflows/vercel-rollback.yml@v1
    with:
      # ⬇️ OBRIGATÓRIO: Nome do seu projeto no Vercel
      vercelProject: "meu-blog-vercel"
      
      # ⬇️ ROTAS TÍPICAS PARA BLOG
      routes: "/,/posts,/sobre,/contato,/api/posts"
      
      # ⬇️ CONFIGURAÇÕES OTIMIZADAS PARA BLOG
      healthCheckTimeout: 30        # Timeout padrão para conteúdo
      maxRetries: 3                 # Tentativas padrão
      monitoringDurationMinutes: 20 # Monitoramento mais curto
      
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

# ========================================
# ROTAS IMPORTANTES PARA BLOG
# ========================================
#
# Páginas Principais:
# / - Homepage
# /posts - Lista de posts
# /sobre - Página sobre
# /contato - Formulário de contato
# /categorias - Categorias do blog
#
# APIs Comuns:
# /api/posts - Listagem de posts
# /api/comments - Sistema de comentários
# /api/newsletter - Newsletter
# /api/contact - Formulário de contato
#
# ========================================
