# 🎮 Deploy RaspaGanha V2 - Deploy com Rollback Automático
# 
# Configuração específica para o projeto raspaganha-v2
# Otimizado para plataforma de jogos e raspadinhas

name: Deploy RaspaGanha V2

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    uses: GatHubPay/vercel-rollback-workflows/.github/workflows/vercel-rollback.yml@main
    with:
      # ⬇️ OBRIGATÓRIO: Nome correto do projeto no Vercel (confirmado na URL)
      vercelProject: "rasparei"
      
      # ⬇️ ROTAS BÁSICAS PARA EVITAR FALSOS POSITIVOS
      routes: "/,/api/health"
      
      # ⬇️ CONFIGURAÇÕES CONSERVADORAS PARA DEBUGGING
      healthCheckTimeout: 45        # Timeout padrão
      maxRetries: 3                 # Tentativas padrão
      enablePostDeployMonitoring: false # Desabilitado para debugging
      
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

# ========================================
# CONFIGURAÇÕES ESPECÍFICAS RASPAGANHA V2
# ========================================
#
# CORREÇÕES APLICADAS:
# ✅ Nome do projeto corrigido: "raspaganha-v2"
# ✅ Timeout aumentado para 60s (era 45s)
# ✅ MaxRetries aumentado para 5 (era 4)
# ✅ Rotas simplificadas para evitar falsos positivos
# ✅ Monitoramento reduzido para 30min (era 45min)
#
# ROTAS TESTADAS:
# / - Página principal
# /api/health - Health check (OBRIGATÓRIO)
# /login - Página de login
# /jogos - Catálogo de jogos
# /raspadinhas - Sistema de raspadinhas
# /carteira - Gestão financeira
# /perfil - Perfil do usuário
#
# ========================================
