name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: |
            ## 🚀 Vercel Deploy + Rollback Automático ${{ steps.tag.outputs.tag }}
            
            ### ✨ Principais Funcionalidades:
            - Deploy automático no Vercel
            - Health checks inteligentes
            - Rollback automático em falhas
            - Notificações no Telegram
            - Auto-detecção de rotas
            
            ### 📋 Como Usar:
            ```yaml
            jobs:
              deploy:
                uses: SeuUsuario/vercel-rollback-workflows/.github/workflows/vercel-rollback.yml@${{ steps.tag.outputs.tag }}
                with:
                  vercelProject: "meu-projeto"
                secrets:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
                  VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
            ```
            
            ### 📚 Documentação:
            - [README](https://github.com/${{ github.repository }}/blob/${{ steps.tag.outputs.tag }}/README.md)
            - [Guia de Configuração](https://github.com/${{ github.repository }}/blob/${{ steps.tag.outputs.tag }}/docs/SETUP.md)
            - [CHANGELOG](https://github.com/${{ github.repository }}/blob/${{ steps.tag.outputs.tag }}/CHANGELOG.md)
            
          draft: false
          prerelease: false
